version: '3.8'

services:
  taxbot-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - BASE_MODEL=microsoft/deberta-v3-large
      - ACCURACY_THRESHOLD=0.95
      - API_HOST=0.0.0.0
      - API_PORT=8000
    depends_on:
      - redis
      
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: